Revert "Use atomics for protected-ints on other *nixes too (not just FreeBSD)"
This reverts commit ced63e12a245692538b692050034ae700ebfe886.

Didn't work for .cpp files:
stdatomic.h:40:9: error: ‘_Atomic’ does not name a type
typedef _Atomic _Bool atomic_bool