Define HAS_INTTYPES_H too, fixes new MSVC build error
syncterm\bbslist.c(778): error C2146: syntax error:
  missing ')' before identifier 'SCNx8

We aren't defining this standard format macro in gen_defs.h (maybe we should
be?) - but as long as MSVC has inttypes.h, seems we should be using that
instead.